### ISSUE TITLE
`bookOptions` optional parameter of `market()` should allow one to load a market with a volume/price limit

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove#121]
When connecting the API to a market, one does not know a priori how many offers should be loaded. The user knows however how much liquidity she wants to access:
* Taker side
  * If selling `V` base tokens at price `p` one wants to load at least a volume of `V*p` bids.
  * If buying `V` base tokens at price `p` one wants to load at least a volume of `V*p` asks.
* Maker side
  * If posting an offer at price `p` one wants to load at least the offers that are better than `p` (in order to get a meaningful pivot)

Right now one can estimate the number of offers to load using `density`, but this is a coarse approximation.
A very useful feature to have would be to access a market using:

```javascript
MgvAPI.market({base:"WETH", quote:"DAI", volume:1000});
```
or
```javascript
MgvAPI.market({base:"WETH", quote:"DAI", price:0.01});
```

**Comment by jkrivine** [comment]
This issue is related to #96 I think

**Comment by espendk** [comment]
I'll look into this as part of #96.

Re. taker side, it is not the case in the dApp that the volume or price is known when loading the market. The market is loaded before the user enters any values. So I'm not sure how useful the volume parameter is in that situation.

**Comment by espendk** [comment]
@jkrivine Re. the volume, one needs to specify whether it's `base` or `quote` as well as `buy` or `sell`. This is also the case for the existing `Market.estimateVolume` function which has the following signature:

```TypeScript
  async estimateVolume(params: {
    given: Bigish;
    what: "base" | "quote";
    to: "buy" | "sell";
  })
```

 We could reuse that parameter structure for `Mangrove.market`:

```TypeScript
  export type VolumeParams = {
    given: Bigish;
    what: "base" | "quote";
    to: "buy" | "sell";
  };
  
  export type BookOptions = {
    maxOffers?: number;
    chunkSize?: number;
    neededVolume?: VolumeParams;
  };
```

Then your taker side examples become:
```TypeScript
mgv.market({ base: "TokenA", quote: "TokenB", bookOptions: { neededVolume: { given: 1000, what: "base", to: "sell"}} });
mgv.market({ base: "TokenA", quote: "TokenB", bookOptions: { neededVolume: { given: 1000, what: "base", to: "buy"}} });
```

What do you think?
