### ISSUE TITLE
`LiquidityProvider` should provide a `consoleAsks/Bids` function

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove#148]
Right now one can do `lp.market.consoleAsks()` which pretty prints the cached `asks` of the market. Calling `lp.consoleAsks()` should do the same but restricted to the asks posted by the liquidity provider.

**Comment by dontrolle** [comment]
This issue seems like a **good first issue** for newcomers, but could maybe do with a bit more spec about what you'd like, @jkrivine to help. :)

**Comment by jkrivine** [comment]
I can't add much more than the above succinct description. The `market` class provides a `consoleAsks` and `consoleBids` function to pretty print the list of offers in the order book cache. 
I suggest that the `liquidityProvider` class provides also a similar function but this time restricted to offers owned by `liquidityProvider.logic`
