### ISSUE TITLE
`market.subscribe` should return a user friendly `mgvData` in case of `OfferFail`

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove#167]
Currently the returned event is :
`{type:'OfferFail', ba:'asks'|'bids', taker:string, 'takerWants':Big, takerGives:Big, mgvData:string, offer:Market.Offer} `
where `mgvData` is a bytes32 string. One should use `ethers.utils.parseBytes32String()` to return a human readable explanation

**Comment by espendk** [comment]
Seems closely related to #186
