### ISSUE TITLE
Failing offer bot

### ISSUE THREAD

**Issue by dontrolle** [mangrovedao/mangrove#187]
To
* harden our components running in production, and,
* create more realistic noise in our order books

it would be helpful to have a bot, which posts failing offers at regular intervals and reports if they aren't cleaned within a certain timeframe.

**Comment by dontrolle** [comment]
It is part of solving this issue to figure out how to identify and produce offers, which will fail when posted.

This issue currently tracks the work from designing the functionality and workings of the bot, accross implementing it, to deploying on our hosting provider.

The template for bots, here https://github.com/mangrovedao/mangrove/tree/master/packages/bot-template, should give an idea about how to setup the scaffolding for implementing a bot. 

But do look at how one of the bots, which are working in prod (e.g., updategas-bot, cleaning-bot) perform. And although we try to keep `template-bot` updated, there *may* also have been updates to the scaffolding which isn't reflected in `template-bot`. 

Should it be found in the process of working on this issue, that the `template-bot` is of no help, then it should be considered whether it should rather be removed from the codebase.

**Comment by jkrivine** [comment]
Any offer posted without access to liquidity will fail when matched. For instance in the api:
```typescript
let mgv = await Mangrove.connect({ signer: wallet });

//connecting mgv to a market
let market = await mgv.market({ base: "DAI", quote: "USDC" });

// create a simple LP on `market`
let directLP = await mgv.liquidityProvider(market);
//
////Ask on market (promise base (DAI) in exchange of quote (USDC))
//// LP needs to approve Mangrove for base transfer (skipping this part will ensure offers posted by this LP will fail)

// // querying mangrove to know the bounty for posting a new Ask on `market`
let prov = await directLP.computeAskProvision();
tx = await directLP.fundMangrove(prov);
await tx.wait();
//
// //Posting a new Ask (that will fail)
const { id: ofrId } = await directLP.newAsk({ wants: 105, gives: 104 });
```

**Comment by peterMangrove** [comment]
@jkrivine Can you take a look at the bot. Just to see that it does what you think it should do.  Troels and Lasse have already reviewed the actual code, but we would like to be sure, that the actual function of the bot is correct.

**Comment by espendk** [comment]
@peterMangrove This issue is done, right?

**Comment by peterMangrove** [comment]
> @peterMangrove This issue is done, right?

Yes, i'll close the issue
