### ISSUE TITLE
Test inclusion of both node 16.x and 17.x in CI for mangrove.js

### ISSUE THREAD

**Issue by dontrolle** [mangrovedao/mangrove#190]
**Is your feature request related to a problem? Please describe.**
Node 16.x is current LTS, but we'd like to shift to node 17.x. We've noted problems with using node 17 in the dApp against Heroku. For this repo, we're considering including testing against node 17.x in CI. This has to be weighed against the time it takes to run CI, however.

**Describe the solution you'd like**
Add node 17.x to the `node-version` matrix in https://github.com/mangrovedao/mangrove/blob/master/.github/workflows/node.js.yml, and evaluate the time it adds to an overall CI run. The critical path is from push/creation of PR to merge.

**Describe alternatives you've considered**
As an alternative, consider only making a CI-run with node version 17.x a few times a day.

**Comment by espendk** [comment]
Many of the tests here are only targeted development, QA, and our own bot environments, not various user environments. For these I think we only need to test against the node version the dev team uses. So maybe it's only mangrove.js where we need to consider multiple node versions?

**Comment by espendk** [comment]
I interpreted the 👍 on my previous comment as assent, so I've updated the title to narrow the scope.
