### ISSUE TITLE
ob-filler bot bootstrap problem when computing reference price

### ISSUE THREAD

**Issue by akettal** [mangrovedao/mangrove#192]
**Is your feature request related to a problem? Please describe.**
ob-filler (order book filler) bot has a bootstrap problem. To compute new offers price, it needs a reference price that is currently fetched from existing offers in Mangrove order book. Consequently, ob-filler bot cannot create new orders and fill the book when Mangrove order book is empty.

**Describe the solution you'd like**
For every pair the bot is working on, when Mangrove order book is empty, fetch the price from an external source and use it as a reference price (see https://github.com/mangrovedao/mangrove/blob/master/packages/obfiller-bot/src/OfferMaker.ts#L101).

To be consistent, as the mangrove-dapp is [already using cryptocompare API](https://github.com/mangrovedao/mangrove-dApp/blob/master/src/services/crypto.ts), we should stick with it as an external market info provider. 

**Describe alternatives you've considered**
It is always possible to compute a reference price without external information, but it will be much less accurate. The overhead of using an external source is minimal.

**Comment by espendk** [comment]
Will be addressed as part of
- mangrovedao/mangrove-tasks#13
