### ISSUE TITLE
Get ingoing token amount for a given outgoing token amount

### ISSUE THREAD

**Issue by johanleroch** [mangrovedao/mangrove#200]
**Is your feature request related to a problem? Please describe.**
As a user I want to be able to buy as many A tokens as I can afford with my B tokens.
Let's take the example of a user who wants the maximum WETH he can afford to buy with the USDC he has in his wallet. (imagining the presence of a "max" button in the WETH input field in the "buy" case).

I got the WETH ingoing amount for my outgoing USDC by using estimateVolume [like that](https://github.com/mangrovedao/mangrove-dApp/blob/fe1c69f5744b3cb570af177f461049d9b79474db/src/components/TradeActionBox/index.tsx#L495):

`      const maxIngoingAmount = estimateVolume({
        given: outgoingTokenBalance,
        what: "quote",
        to: "sell",
      });`
_How much WETH can I get if I sell this amount of USDC_

This is a roundabout way that is also inaccurate because the calculation is not based on the right offers.

**Describe the solution you'd like**
I'd would be ideal to have a function: 

- which takes the outgoing token amount and returns the ingoing token amount

**Additional context**
![image](https://user-images.githubusercontent.com/7213352/153872032-a51b5860-5f9d-4aec-af25-218dbf834fef.png)

**Comment by adhusson** [comment]
It seems like the call you are doing is correct. On a WETH-USDC market, the call will take the `asksSemibook` (a list of offers that promise WETH in return for USDC) and estimate how much WETH you'd receive if you kept buying offers until all your USDC was gone (more precisely, it should reproduce what would happen if you did a market order on the WETH/USDC mangrove offer list with `wants=<huge number>`, `gives=<outgoingTokenBalance>`, `fillWants=false`.

Pinging @espendk I'm having trouble reading the new syntax for https://github.com/mangrovedao/mangrove/blob/master/packages/mangrove.js/src/semibook.ts#L293 it should be the same behavior as before right?

**Comment by vd1** [comment]
Hi I am not sure this is a relevant point of terminology, but the standard word pair is "outgoing/incoming" = "to be sent/to be received"

**Comment by espendk** [comment]
> Pinging @espendk I'm having trouble reading the new syntax for https://github.com/mangrovedao/mangrove/blob/master/packages/mangrove.js/src/semibook.ts#L293 it should be the same behavior as before right?

It's the same logic as before, just expressed as a fold instead of a for-loop and more elaborate variable names.
Happy to discuss and improve :-)

**Comment by johanleroch** [comment]
for @adhusson 
What we discussed a while was to have 2 methods like this: 
`estimateVolumeToReceive({given:"base"|"quote",amount:number}) estimateVolumeToSpend({given:"base"|"quote",amount:number})`

**Comment by adhusson** [comment]
May be fixed by 0cbf5af288348dd34dc8c5acd5706e0ea3992bc4 ?
