### ISSUE TITLE
Confirm tx button is flickering

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove#204]
**Describe the bug**
When a tx needs to be approved, the confirm button is accessible, then becomes innacessible and reappears afterwards.

**To Reproduce**
1. Go to the dAPP on any market
2. Click on a trade
3. check the status of the confirm button

**Expected behavior**
It may give the impression one needs to approve the tx twice if the button is clicked the first time

**Comment by jkrivine** [comment]
This might be a metamask related issue

**Comment by johanleroch** [comment]
This is a normal behavior from Metamask. 
It seems that it comes with this [EIP-1559](https://metamask.io/1559/) (now the gas and fees are calculated by default, and when the calculation is in progress buttons are disabled).

If we set a amount higher than needed, we can see the confirm button always enabled.
