### ISSUE TITLE
User balance are not correctly refreshed 

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove#207]
**Describe the bug**
User balance is sometimes not correctly refreshed when changing market. As a consequence, the frontend might believe the user doesn't have the provision to execute a particular trade.

**To Reproduce**
hard to reproduce

**Screenshots**
<img width="1429" alt="Capture d’écran 2022-02-18 à 22 54 02" src="https://user-images.githubusercontent.com/293262/154767239-df9da790-83cc-4937-acaa-132a176f94dd.png">

**Comment by espendk** [comment]
I removed the `flaky test` label which is for tracking CI tests that fail sometimes.

**Comment by espendk** [comment]
Duplicate of https://github.com/mangrovedao/mangrove-dApp/issues/124

I've added a link from there to this.
