### ISSUE TITLE
Mangrove.js depends on an unpublished packages (`commonlib-js`)

### ISSUE THREAD

**Issue by akettal** [mangrovedao/mangrove#220]
**Describe the bug**

mangrove.js NPM package V0.2.0 has a newly introduced dependency on an unpublished package in the monorepo (commonlib.js), and therefore cannot be installed.

**To Reproduce**

1. Publish a new version of `mangrove.js` NPM package from `c52a56` commit;
2. Add this newly published version as a dependency in a JS/TS project.

**Expected behavior**

`yarn install` in the new project works fine.
(@espendk I supposed the unpublished dependency cannot be resolved at install time, correct me if I'm wrong)

**Additional context**

Bug introduced by the logging feature, which adds a dependency to `commonlib-js` to use a wrapper around Winston.

**Comment by espendk** [comment]
> (@espendk I supposed the unpublished dependency cannot be resolved at install time, correct me if I'm wrong)

Pretty sure that was the case, though I don't have the output anymore (should've filed an issue 😔).

**Comment by espendk** [comment]
Copying over some info from chat for later reference (see also PR #221):

@akettal
>  bundledDependencies isn’t the correct solution... (https://yarnpkg.com/getting-started/migration#dont-use-bundledependencies). Will need to publish commonlib-js before founding something better...
> 
> Before that, I tried to unpublish @mangrovedao/mangrove.js (0.3.0) but it fails (Usage: Refusing to delete entire project(s). ).
> I just want to be sure I’m doing anything stupid before --force  it!
> The command I ran: npm unpublish @mangrovedao/mangrove.js@0.3.0 (edited) 


@espendk 
> It seems npm has had issues like this in the past: https://github.com/npm/npm/issues/13500#issuecomment-235726307
> I’ve sent npm support an email (with you cc) and hope they will fix it.

**Comment by espendk** [comment]
Downgrading this as to `High` priority as it is no longer blocking deployment of mangrove.js.

**Comment by espendk** [comment]
Since the Winston logging package doesn't work in the browser, we could consider using [pino](https://github.com/pinojs/pino) instead. They explicitly state that browsers are supported, though it's not clear whether it would work with the browser build system we're using - this needs to be checked.

**Comment by adhusson** [comment]
Should be fixed by [b09d9d6](https://github.com/mangrovedao/mangrove/pull/489/commits/b09d9d6109f7518ff6adffd07697ff78e01d92ea)

**Comment by espendk** [comment]
I just verified that errors are now logged correctly with the `[error]` prefix where "`error`" is colored red.
Closing the issue.
