### ISSUE TITLE
Update updategas-bot to use Polygon v2 gasstation format

### ISSUE THREAD

**Issue by dontrolle** [mangrovedao/mangrove#222]
Polygon has updated their gasstations to a v2-format (both for Mumbai and Mainnet). We should update the `updategas-bot` to use those. 

See https://gasstation-mumbai.matic.today/v2 and here https://docs.polygon.technology/docs/develop/tools/polygon-gas-station/

**Comment by espendk** [comment]
Gas update bot is not required for public testnet, so I've moved this to the next milestone where it is required.

**Comment by dontrolle** [comment]
This method https://github.com/mangrovedao/mangrove/blob/a6b3420ab2375df778a7515e1f6eab587b37b6fa/packages/bot-updategas/src/GasUpdater.ts#L129, is where the `updategas-bot` queries the external oracle. Work back from there and update what may be needed also in config.
