### ISSUE TITLE
Fix parallel development of mangrove.js & contracts known by mangrove.js. 

### ISSUE THREAD

**Issue by adhusson** [mangrovedao/mangrove#248]
mangrove.js has a `hardhatAddresses.json` file containing the addresses of several contracts that get deployed on local nodes, generated when building `mangrove.js` and copied to `dist/` as part of the `tsc` compilation in `mangrove.js`. 

When those addresses change (due to local dev work), one must 1) use a local copy of mangrove.js (not the npm package), and 2) rebuild mangrove.js.

This issue is for discussing & implementing a fix.

Some points:
1) The solution should be compatible with people developing their own contracts (eg maker contracts); they may not develop from `mangrove-solidity` nor use `hardhatAddresses.json`.
2) The solution should require minimal "local-only setup" eg. it should be compatible with using the npm version of mangrove.js. This is not a hard requirement -- you can force people to use `npm link` and manually rebuild, but it's less nice.

It seems important to have that before opening up mangrove.js more publically because it is a common friction during development.

My current preferred idea: implement a very lightweight ENS-like `string->address` mapping. Have all hardhat node pathways begin with deploying this ENS-like mapping and register all newly deployed contracts through their names (eg. `ens.register("Mangrove",address(this))`).

Pros: 
* When on a local network, mangrove.js always knows the correct address for each contract.
* Small overhead for developers who deploy their own contracts

Cons:
* Why not use the full ENS system?
* Running your node without deploying the ENS-like system will break local mangrove.js usage

Happy to hear everyone's thoughts!

**Comment by espendk** [comment]
This is closely related to https://github.com/mangrovedao/mangrove-tasks/issues/26 .

**Comment by espendk** [comment]
I updated the description to match how `hardhatAddresses.json` is currently build.

**Comment by dontrolle** [comment]
At some point we should revise this issue to our latest understanding of the split up of repos ( @espendk and @dontrolle ).

**Comment by adhusson** [comment]
I think we can close this now -- the repo has been split, there is a lightweight ENS for testing.
