### ISSUE TITLE
MgvOracle should emit events to allow tracking state off chain

### ISSUE THREAD

**Issue by dontrolle** [mangrovedao/mangrove#250]
**Is your feature request related to a problem? Please describe.**
The `MgvOracle` should emit events that allow off-chain monitoring of state changes regarding gas and density.

**Describe the solution you'd like**
* For the gasprice, the `MgvOracle` must emit `SetGasprice(uint)` whenever gasprice is updated.

**Additional context**
Similarly, in the future, `MgvOracle` should emit events for density-updates (the oracle does not control `density`, right now), by emitting a similarly named event whenever the density is updated. See #377 concerning `MgvOracle` and `density`.

This has ties with our monitoring solutions.

**Comment by adhusson** [comment]
Awesome :) Some suggestions:
1) I would immediately add all relevant emits (eg SetDensity)
2) I would split commits for easier auditing later into a) commits that modify core .sol files, b) commits that modify tests and/or addresses and/or any infrastructure stuff.
