### ISSUE TITLE
mangrove.js: Add tests for all public methods in `market.ts` and `semibook.ts`

### ISSUE THREAD

**Issue by dontrolle** [mangrovedao/mangrove#252]
**Is your feature request related to a problem? Please describe.**
The dearth of tests of `market.ts` and `semibook.ts` has caused us pain several times. At the same time, the development pace on these files are is still high, and for some commits, we are not testing changes and additions, because it would require major test infrastructure to add those tests. This is unsustainable in the longer run. 

This issue seeks that we build a foundation to grow from.

**Describe the solution you'd like**
Add tests, at least one non-trivial, for each public method in `market.ts` and `semibook.ts`.

# Sub-tasks
- [x] Create sub-tasks for all currently untested public methods in `market.ts`
- All public methods have been tested, except "onceWithTxPromise" and "unsubscribe"
- [x] Create sub-tasks for all currently untested public methods in `semibook.ts`

**Comment by peterMangrove** [comment]
Look at the PR: https://github.com/mangrovedao/mangrove/pull/590
