### ISSUE TITLE
mangrove.js: Move types to a central location

### ISSUE THREAD

**Issue by adhusson** [mangrovedao/mangrove#30]
@espendk said: "Also, we could consider letting the types.ts just import and reexport the types. This would allow the types to be defined where they are used, eg in market.ts."

**Comment by adhusson** [comment]
Tried to implement that in d1f332a26132b3a7cef975cdf13873ab17cd989a @espendk requesting review!

**Comment by espendk** [comment]
Much more consistent now I thinkg.

Two  comments:

1. What is gained by having all types in one place? I'm assuming it somehow makes things easier for consumers of mangrove.js.

2. The "namespacing" can be a bit redundant in places, e.g. in market.ts:
  ```
    #mapConfig(
      ba: "bids" | "asks",
      cfg: Types.Mangrove.rawConfig
    ): Types.Mangrove.localConfig {
  ```
  
  The `Types.` prefix does not add any information does it?

**Comment by vd1** [comment]
I am not sure this is related but i get the following error when running printOrderBook.ts:

**Comment by espendk** [comment]
Namespaces have been subsumed by modules (see e.g. https://www.youtube.com/watch?v=tXK50czRbdA&t=990s), so I think we should try to avoid them.


One concrete problem I'm having with namespaces is defining a **class** (e.g. `Semibook`) in a different file from the one that gathers the types in a namespace (e.g. `market.ts`). The usual `export type ...` does not work.

This seems to force us to either avoid classes or to put a whole namespace in a single file, resulting in ginormous files...
