### ISSUE TITLE
scripts/helper.js

### ISSUE THREAD

**Issue by vd1** [mangrovedao/mangrove#39]
In scripts/helper.js line 8-12:

`function tryGet(cfg, name) {
  if (cfg.has(name)) {
    return cfg.get(name);
  }
}`

how do we handle the case where cfg doesn't have what we are looking for?

**Comment by jkrivine** [comment]
you can edit the `config/[network]/[chain].json` file with the relevant information. If needed add the abi files in the `config/[network]/abis/`
