### ISSUE TITLE
Hardhat has broken dependencies and compiles too many solidity files

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove#397]
**Describe the bug**
Modifying one solidity file (for instance in tests) induces hardhat to recompile *every* solidity file

**Expected behavior**
Something must be broken in the way hardhat computes dependencies: changing one solidity file should yield the compilation of that file (and dependencies) only.

**Comment by dontrolle** [comment]
@jkrivine Just be clear - you've set the Hackathon milestone, so unless I can think of something in a moment, I'm going to let this issue rest until we've hit the coming milestone, right? 😊

**Comment by espendk** [comment]
Removing assignee as this task is for a future milestone and we don't know who'll be looking at it.

**Comment by vd1** [comment]
I think one says "too many files" or simply "too much", much is of type "continuous quantity"

**Comment by jkrivine** [comment]
Since we are moving to foundry I propose to close this issue
