### ISSUE TITLE
mangrove-solidity: Fix and reenable flaky test in test-defensive

### ISSUE THREAD

**Issue by dontrolle** [mangrovedao/mangrove#451]
**Describe the bug**
After a number of failing CI-runs, it was determined that the [`.once()` event-listener in `test-defensive.js` ](https://github.com/mangrovedao/mangrove/blob/29192e3db35979d85811be2599564a631b04259a/packages/mangrove-solidity/test/test-defensive.js#L50) would sometime fail to fire, leading the test to stall indefinitely. 

**To Reproduce**
Uncomment the commented test-case ""Price fed strat" in `packages/mangrove-solidity/test/test-defensive.js` and run the tests in CI (maybe several times) - local runs have typically failed to repro the problem.

**Expected behavior**
The test never stalls.

Several lines of attack are possible here: 
* Investigate why the event-listener doesn't fire sometimes
* Ensure that the test times out, even if the event is not received.
* Use a different pattern / rewrite the test.

**Comment by jkrivine** [comment]
this test is no longer part of the test suite.
