### ISSUE TITLE
Add more informations about a TX to the user

### ISSUE THREAD

**Issue by johanleroch** [mangrovedao/mangrove#491]
**Is your feature request related to a problem? Please describe.**
Many users during Julien's interviews complained about Orders not being fulfilled as expected (for ex with gas consumed but no tokens in return, or just got partially what they asked for).
They think the product doesn't work while it is a misunderstanding of the functioning on their part.

So after discussing with @jkrivine, we thought it would be interesting to add some information in an OrderResult to retrieve the list of success/failed makers.

I think this will have the benefit of being quite transparent and educational on how Mangove works, it could arouse the curiosity of users for more advanced use cases.

**Describe alternatives you've considered**

**Additional context**
Many of them mentioned the "order routing" feature from [Paraswap](https://www.paraswap.io/) -> could improve the understanding of Mangrove
![telegram-cloud-photo-size-4-5821320779927763405-y](https://user-images.githubusercontent.com/7213352/171844856-81bb115a-e254-4146-9830-a56bfb0ee893.jpg)
![telegram-cloud-photo-size-4-5821320779927763406-y](https://user-images.githubusercontent.com/7213352/171844918-d532f038-db1e-4ee6-b9ce-f8fa6d764548.jpg)

**Comment by jkrivine** [comment]
In the `sell` and `buy` functions of `Market.ts` the loop that browse through tx log should collect all `OfferSuccess` and `OfferFail` events to create two lists that can be made available to the user to give more feedback about what happened:
 * no offer matched the price (too much slippage) in which case the lists are empty
 * some offer failed (and gas was compensated)
 * how many offers where consumed etc.
