### ISSUE TITLE
[mangrove-solidity] Move TestUtils methods to MgvReader

### ISSUE THREAD

**Issue by adhusson** [mangrovedao/mangrove#503]
Functions such as `makerOf` and `hasOffer` in TestUtils seem like they should be implemented inside `MgvReader` since they seem so useful in tests.

They could be part of Mangrove itself (so they cost less when actually executed on-chain), but as always there is additional risk.

What do you think?

**Comment by jkrivine** [comment]
Yes. Not much risk associated to a `view` function. I think there are many useful functions we could integrate there. 
```
hasOffer: address -> address -> uint -> bool // whether an offerId exists (live or dead) in an OfferList
isLiveOffer: address -> address -> uint -> bool // whether an offerId is live in an OfferList
makerOf: address -> address -> uint -> address  // returns the owner of an offer
minDensityAtOfferList: address -> address -> uint // returns current required min density to post in an OfferList
provisionAtOfferList: address -> address -> uint -> uint // returns the current provision required for the given gasreq
```

**Comment by jkrivine** [comment]
`minDensityAtOfferList` should be actually `minVolumeAtOfferList` -> given offer gasreq, returns the min `gives` volume required.
`hasOffer`, `isLive` etc are all doable onchain obviously, but require to be aware of encodings.

**Comment by adhusson** [comment]
minVolume is added in mangrovedao/mangrove-core#45
