### ISSUE TITLE
`estimateGas` in `market.ts` results in taker out of gas when `takerWants` is too low

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove#89]

**Comment by jkrivine** [comment]
Currently the method to estimate gas of a taker order returns a too coarse under approximation that results in taker reverting for an out of gas transaction (because the method assumes a linear scaling of density). A solution is to systematically add `gasmax` to the estimation to cover for a partial fill

**Comment by dontrolle** [comment]
A question: You suggest adding `gasmax[ to every estimate in `estimateGas` (as I read the notes). Wouldn't that be a bit much of an over-estimate? 🤔 

Looking at the config, I (maybe naively) thought that this is a symptom of indicating that the `offer_gasbase` should be increased for the pair?

**Comment by jkrivine** [comment]
yes agreed. Solution 1 is a big over approx. I would much prefer 2 or 3 if doable

**Comment by jkrivine** [comment]
`offer_gasbase` is the cost of entering the marketOrder and executing the transfers. The `out of gas` exception here comes from the partial fill, not from an under estimation of the overhead

**Comment by dontrolle** [comment]
> `offer_gasbase` is the cost of entering the marketOrder and executing the transfers. The `out of gas` exception here comes from the partial fill, not from an under estimation of the overhead

Got it. 👍 Makes sense.

**Comment by dontrolle** [comment]
Ok. Got pulled away in various directions, but now have focus time to look at this again.

Concretizing your suggestion 2) how about we do something like the following? ->

* add `max_gasreq` as a field of `Market`.
* listen for new offers, i.e., `OfferWrite`'s, and update `max_gasreq` to max of last seen and `offer.gasreq`.
   - easiest way to do this seems to be to add this `max_gasreq` update beside handling user-subscriptions in [`Market.#semibookEventCallback`](https://github.com/mangrovedao/mangrove/blob/fa1f1052583402cf239436aa25398243071b25fa/packages/mangrove.js/src/market.ts#L294)?
* in `estimateGas` add `max_gasreq` to the current estimate (which is `volume/density + offer_gasbase`).

How does that sound?

**Comment by jkrivine** [comment]
When updating `max_gasreq` you should maybe consider only the `gasreq` of the offers that are within a reasonable range. Otherwise you could grief the system by posting an offer far from the mid price with a huge amount of `gasreq` (say `gasmax`)

**Comment by dontrolle** [comment]
Hmmm, yeah I guess we could experience such griefing.

We don't currently maintain a mid price for the market, although it can, of course, easily be calc'ed by looking at the best offers on each side of the OB (from the takers side). Maybe we want to keep the mid price cached as well? (Or maybe postpone that.)

We need to define "offers within a reasonable range of the mid price". Given the mid price, do you have something in mind of how to identify reasonable offers (for this calculation)? You have more experience looking at order books than I.

Thinking a little about it, I'm worried about:
1. degenerate OBs, e.g., where there's a jump in price, from the best price and up
2. "an unreasonable offer", i.e., an offer, which we've looked away from in the calc for `max_gasreq`, which sits in the OB, and that later become "reasonable". In my draft solution (which I've coded up fast locally), I update `max_gasreq` mainly by listening to `offer_write`'s

Going off of my worry no. 2, the more I think about, we could avoid some problems by computing `max_gasreq` on-demand, by looking at the current OB, when `estimateGas()` is called. It would add a little bit of compute overhead, but it may be enough to look at the offers we have in the Semibook-caches for the Market. 

I'd love your thoughts on that.

For now, I'll try to code that up, as well as a test or two.
